version: '3'
services:
  peer1: &peer
    command: /nudocs/nudocs
    expose:
    - "3333"
    networks:
    - nudocs-net
    image: centos:7.4.1708
    volumes:
    - ".:/nudocs"
  client1: &client
    command: /nudocs/client/client -h peer1 -p 3333 -f /nudocs/test/test.txt
    networks:
    - nudocs-net
    image: centos:7.4.1708
    volumes:
    - ".:/nudocs"


  peer2: *peer
  peer3: *peer
  peer4: *peer
  peer5: *peer
  client2: *client
  client3: *client
  client4: *client
  client5: *client

networks:
  nudocs-net:
    driver: bridge
