version: '3'
services:
  peer1: &peer
    command: /nudocs/nudocs
    expose:
    - "3333"
    networks:
    - nudocs-net
    image: centos:7.4.1708
    volumes:
    - ".:/nudocs"
  peer2: *peer
  peer3: *peer
  peer4: *peer
  peer5: *peer

networks:
  nudocs-net:
    driver: bridge
